### ISSUE TITLE
Kurang pembahasan

### ISSUE THREAD

**Issue by Digisata** [naya-kursus/kurikulum#26]
Untuk materi [Git kolaborasi](https://github.com/naya-kursus/kurikulum/blob/76ed5ae8bdb6a76f84af104d8eb481ce7304ca5b/backend-go/README.md?plain=1#L32) masih belom ada pembahasnnya ?

**Comment by nayatech-id** [comment]
Materi tersebut sebetulnya lanjutan dari materi Dasar Git dan Github.
Akan dibahas bersama dengan kelas Frontend juga.
Jadi, pembahasan akan dimasukkan nanti setelah melihat perkembangan kelas backend dan frontend.

Terima kasih telah menambahkan issue ini.
Saya izin menutupnya karena pertanyaan sudah terjawab.

**Comment by Digisata** [comment]
Baik terimakasih, izin close issue,.....
